if STRINGS.CHARACTERS.WALANI == nil then STRINGS.CHARACTERS.WALANI = {
  DESCRIBE = {},
} end -- DLC002
if STRINGS.CHARACTERS.WARLY == nil then STRINGS.CHARACTERS.WARLY = {
  DESCRIBE = {},
} end -- DLC002
if STRINGS.CHARACTERS.WOODLEGS == nil then STRINGS.CHARACTERS.WOODLEGS = {
  DESCRIBE = {},
} end -- DLC002
if STRINGS.CHARACTERS.WILBA == nil then STRINGS.CHARACTERS.WILBA = {
  DESCRIBE = {},
} end -- DLC003
if STRINGS.CHARACTERS.WARBUCKS == nil then STRINGS.CHARACTERS.WARBUCKS = {
  DESCRIBE = {},
} end -- DLC003
-------------------------------
-- Prefab
STRINGS.NAMES.PIGCROWNHAT = "Royal Crown"
STRINGS.RECIPE_DESC.PIGCROWNHAT = "L'etat, C'est Moi!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGCROWNHAT = "I am the King of this world!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WALANI.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WILBA.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
