if STRINGS.CHARACTERS.WALANI == nil then STRINGS.CHARACTERS.WALANI = {
  DESCRIBE = {},
} end -- DLC002
if STRINGS.CHARACTERS.WARLY == nil then STRINGS.CHARACTERS.WARLY = {
  DESCRIBE = {},
} end -- DLC002
if STRINGS.CHARACTERS.WOODLEGS == nil then STRINGS.CHARACTERS.WOODLEGS = {
  DESCRIBE = {},
} end -- DLC002
if STRINGS.CHARACTERS.WILBA == nil then STRINGS.CHARACTERS.WILBA = {
  DESCRIBE = {},
} end -- DLC003
if STRINGS.CHARACTERS.WARBUCKS == nil then STRINGS.CHARACTERS.WARBUCKS = {
  DESCRIBE = {},
} end -- DLC003
-------------------------------
-- Prefab
STRINGS.NAMES.PIGCROWNHAT = "Royal Crown"
STRINGS.RECIPE_DESC.PIGCROWNHAT = "L'etat, C'est Moi!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGCROWNHAT = "I am the King of this world!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WALANI.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WILBA.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"


STRINGS.NAMES.ANTMASKHAT = "Mant Mask"
STRINGS.RECIPE_DESC.ANTMASKHAT = "A face only a Mant could love."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTMASKHAT = "There's still some goo stuck to the insides."
STRINGS.CHARACTERS.WALANI.DESCRIBE.ANTMASKHAT = "Sorry bug-dude."
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.ANTMASKHAT = "Rather morbid depths I've sunk to."
STRINGS.CHARACTERS.WARLY.DESCRIBE.ANTMASKHAT = "The pith has been removed."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ANTMASKHAT = "Mine helm would have sufficed."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ANTMASKHAT = "A hollowed out head. Don't ask where I got it."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ANTMASKHAT = "This seems a little mean."
STRINGS.CHARACTERS.WENDY.DESCRIBE.ANTMASKHAT = "The mind that dwelt within is long gone."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ANTMASKHAT = "This may be slightly unethical."
STRINGS.CHARACTERS.WILBA.DESCRIBE.ANTMASKHAT = "WILBA WEAR THE HEAD OF MINE ENEMIES"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ANTMASKHAT = "This is the nastiest thing I've ever made."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ANTMASKHAT = "Make Wolfgang look like Bug Man."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ANTMASKHAT = "I hope no one recognizes this guy."
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.ANTMASKHAT = "T'mask yer ugly mug."
STRINGS.CHARACTERS.WX78.DESCRIBE.ANTMASKHAT = "DECORATION MODULE ACQUIRED"

STRINGS.NAMES.ANTSUIT = "Mant Suit"
STRINGS.RECIPE_DESC.ANTSUIT = "Walk a mile in a Mant's carapace."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTSUIT = "It's brittle."
STRINGS.CHARACTERS.WALANI.DESCRIBE.ANTSUIT = "Nice threads!"
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.ANTSUIT = "When in Rome..."
STRINGS.CHARACTERS.WARLY.DESCRIBE.ANTSUIT = "There's no meat inside."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ANTSUIT = "This armor is not worthy of a shieldmaiden!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ANTSUIT = "The indignities I've suffered..."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ANTSUIT = "We could always use a spare thorax."
STRINGS.CHARACTERS.WENDY.DESCRIBE.ANTSUIT = "As hollow as my heart."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ANTSUIT = "A hollowed out arthropod."
STRINGS.CHARACTERS.WILBA.DESCRIBE.ANTSUIT = "WILBA AM MERELY PLAYER"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ANTSUIT = "This is the worst."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ANTSUIT = "Wolfgang just want to fit in."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ANTSUIT = "This feels a tad psychotic."
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.ANTSUIT = "'Tis an unpleasant bus'niss."
STRINGS.CHARACTERS.WX78.DESCRIBE.ANTSUIT = "INEFFICIENT PROTECTIVE CASING"
