-------------------------------
-- Prefab
STRINGS.NAMES.PIGCROWNHAT = "Royal Crown"
STRINGS.RECIPE_DESC.PIGCROWNHAT = "L'etat, C'est Moi!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGCROWNHAT = "I am the King of this world!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!" -- Wigfrid
if STRINGS.CHARACTERS.WALANI then STRINGS.CHARACTERS.WALANI.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!" end -- DLC002
if STRINGS.CHARACTERS.WILBA then STRINGS.CHARACTERS.WILBA.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!" end -- DLC003
STRINGS.CHARACTERS.WINONA.DESCRIBE.PIGCROWNHAT = "I am the Queen of this world!" -- DST
